(feat): add all files sprint 2
ClevertecFrontendLab/Evgenii77777 pull request #2
Opened 2024-02-26 10:04 UTC by Evgenii77777

почему не проходит последний тест ,я не знаю , обернул и в suspense , и lazy main ,но все равно не видит loader, хотя на скринах он есть

2024-02-26 10:07 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 85%.
Общее количество тестов: 7.
Количество непройденных тестов: 1.
***
**change-pass-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/change-pass-error-1.png)
***
**change-pass-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/change-pass-error-2.png)
***
**change-pass-error-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/change-pass-error-3.png)
***
**change-pass-error-4.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/change-pass-error-4.png)
***
**change-pass-error-5.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/change-pass-error-5.png)
***
**change-pass-error-6.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/change-pass-error-6.png)
***
**change-pass-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/change-pass-success-1.png)
***
**change-pass-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/change-pass-success-2.png)
***
**change-pass-success-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/change-pass-success-3.png)
***
**login-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/login-error-1.png)
***
**login-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/login-error-2.png)
***
**login-remember-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/login-remember-1.png)
***
**login-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/login-success-1.png)
***
**reg-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/reg-error-1.png)
***
**reg-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/reg-error-2.png)
***
**reg-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/reg-success-1.png)
***
**reg-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/reg-success-2.png)
***
**sprint 2 -- change-pass-error (failed).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708942021/sprint%202%20--%20change-pass-error%20(failed).png)

2024-02-26 15:10 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 85%.
Общее количество тестов: 7.
Количество непройденных тестов: 1.
***
**change-pass-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/change-pass-error-1.png)
***
**change-pass-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/change-pass-error-2.png)
***
**change-pass-error-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/change-pass-error-3.png)
***
**change-pass-error-4.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/change-pass-error-4.png)
***
**change-pass-error-5.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/change-pass-error-5.png)
***
**change-pass-error-6.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/change-pass-error-6.png)
***
**change-pass-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/change-pass-success-1.png)
***
**change-pass-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/change-pass-success-2.png)
***
**change-pass-success-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/change-pass-success-3.png)
***
**login-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/login-error-1.png)
***
**login-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/login-error-2.png)
***
**login-remember-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/login-remember-1.png)
***
**login-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/login-success-1.png)
***
**reg-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/reg-error-1.png)
***
**reg-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/reg-error-2.png)
***
**reg-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/reg-success-1.png)
***
**reg-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/reg-success-2.png)
***
**sprint 2 -- change-pass-error (failed).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1708960228/sprint%202%20--%20change-pass-error%20(failed).png)

2024-02-26 15:14 UTC, Pred1993 commented
![Снимок экрана 2024-02-26 181226](https://github.com/ClevertecFrontendLab/Evgenii77777/assets/103571130/fe5e99fd-ba87-4be3-94a8-cf5f1bbb3d4c)
Бэкграунд не как в макете, отсутствует e-mail, компонент проверочного кода не соответствует макету, неужели ты сам этого не видишь и вновь пушишь такую халтуру?

2024-02-26 15:21 UTC, Pred1993 requested changes
Исправляй UI

2024-02-26 20:09 UTC, byshlata requested changes

2024-02-26 20:09 UTC, byshlata commented on src/components/icon-error/icon-error.jsx
> +        location.pathname !== '/result/error-login' &&
наверное, это должно быть в переменных PATH быть, и можно и в урле использовать и тут

2024-02-26 20:09 UTC, byshlata commented on src/components/loader/loader.jsx
> +    const defaultOptions = {
вот это можно ввверху сделать, над компонентом, смысл этого тут, это же константа по сути

2024-02-26 20:09 UTC, byshlata commented on src/components/loader/loader.jsx
> +        <>
лишнее это тут

2024-02-26 20:09 UTC, byshlata commented on src/pages/auth-page/auth-page.jsx
> +    const message = useSelector((state) => state.login.message);
это бы вынести отдельно нужно было бы const messageSelector =  (state) => state.login.message

2024-02-26 20:09 UTC, byshlata commented on src/pages/auth-page/auth-page.jsx
> +        } else if (type === 'change' && !isError) {
очень жесткая штука, прям ты через месяц залезешь, сам не вспомнишь, что к чему.

2024-02-26 20:09 UTC, byshlata commented on src/pages/main-page/main-page.tsx
> +            sessionStorage.getItem('JWTSession') === 'undefined'
почитай пропсевдоистину, псевдоложь

2024-02-26 20:09 UTC, byshlata commented on src/pages/result-page/result-page.jsx
> +    const { Title, Paragraph } = Typography;
а это в компоненте зачем? это должно быть выше компонента

2024-02-26 20:09 UTC, byshlata commented on src/pages/result-page/result-page.jsx
> +    const path = dataMode.filter((el) => el.type === location.pathname);
очень понятное название переменной

2024-02-26 20:09 UTC, byshlata commented on src/pages/result-page/result-page.jsx
> +            dispatch(changePassword(user));
может тут проще на switch переделать?

2024-02-27 07:03 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 85%.
Общее количество тестов: 7.
Количество непройденных тестов: 1.
***
**change-pass-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/change-pass-error-1.png)
***
**change-pass-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/change-pass-error-2.png)
***
**change-pass-error-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/change-pass-error-3.png)
***
**change-pass-error-4.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/change-pass-error-4.png)
***
**change-pass-error-5.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/change-pass-error-5.png)
***
**change-pass-error-6.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/change-pass-error-6.png)
***
**change-pass-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/change-pass-success-1.png)
***
**change-pass-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/change-pass-success-2.png)
***
**change-pass-success-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/change-pass-success-3.png)
***
**login-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/login-error-1.png)
***
**login-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/login-error-2.png)
***
**login-remember-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/login-remember-1.png)
***
**login-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/login-success-1.png)
***
**reg-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/reg-error-1.png)
***
**reg-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/reg-error-2.png)
***
**reg-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/reg-success-1.png)
***
**reg-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/reg-success-2.png)
***
**sprint 2 -- change-pass-error (failed).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Evgenii77777/1709017418/sprint%202%20--%20change-pass-error%20(failed).png)

2024-02-27 07:50 UTC, byshlata approved these changes

2024-02-27 08:40 UTC, Pred1993 approved these changes

2024-02-27 08:41 UTC, merged