feat(*):sprint 6
ClevertecFrontendLab/Evgenii77777 pull request #4
Opened 2023-03-18 20:43 UTC by Evgenii77777

2023-03-18 20:47 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 25.
Количество непройденных тестов: 5.

2023-03-18 20:54 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 64%.
Общее количество тестов: 25.
Количество непройденных тестов: 9.

2023-03-18 21:00 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 25.
Количество непройденных тестов: 5.

2023-03-18 22:12 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 76%.
Общее количество тестов: 25.
Количество непройденных тестов: 6.

2023-03-18 23:46 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 25.
Количество непройденных тестов: 5.

2023-03-19 07:34 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 76%.
Общее количество тестов: 25.
Количество непройденных тестов: 6.

2023-03-19 07:38 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 76%.
Общее количество тестов: 25.
Количество непройденных тестов: 6.

2023-03-19 07:54 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 96%.
Общее количество тестов: 25.
Количество непройденных тестов: 1.
***
**1-all-buttons.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/1-all-buttons.png)
***
**10-selected-day.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/10-selected-day.png)
***
**11-booking-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/11-booking-error.png)
***
**12-booking-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/12-booking-success.png)
***
**13-booking-edit-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/13-booking-edit-modal-view.png)
***
**14-modal-edited-date.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/14-modal-edited-date.png)
***
**15-rate-modal.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/15-rate-modal.png)
***
**16-rate-modal-mobile.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/16-rate-modal-mobile.png)
***
**17-rate-filled.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/17-rate-filled.png)
***
**18-comments-updated-sort.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/18-comments-updated-sort.png)
***
**2-booking-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/2-booking-modal-view.png)
***
**3-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/3-mobile-view.png)
***
**4-january.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/4-january.png)
***
**5-december-2022.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/5-december-2022.png)
***
**6-february.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/6-february.png)
***
**7-today-is-friday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/7-today-is-friday.png)
***
**8-today-is-saturday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/8-today-is-saturday.png)
***
**9-today-is-sunday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/9-today-is-sunday.png)
***
**booking and book rate -- booking edit modal -- check cancel booking error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20cancel%20booking%20error%20(failed).png)
***
**edit-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679212452/edit-mobile-view.png)

2023-03-19 15:33 UTC, Ivan6813 requested changes

2023-03-19 15:33 UTC, Ivan6813 commented on src/components/about/about.jsx
> +                setIsShowCalendar(true);
такая же функция с 39 по 42 строки, создай вверху функцию и переиспользуй её

2023-03-19 15:33 UTC, Ivan6813 commented on src/components/calendar/calendar.jsx
> +// };
закомментированного кода быть не должно, проверь по всему проекту и удали

2023-03-19 15:33 UTC, Ivan6813 commented on src/components/card/card.jsx
> +              setBookId(e.target.id);
функция повторяется несколько раз, выноси вверх и переиспользуй

2023-03-19 15:33 UTC, Ivan6813 commented on src/components/error/booking-error/booking-error.jsx
> +        {message && status === 'message' && isSuccess && 'Спасибо, что нашли время оценить книгу!'}
выглядит сложно и плохо читается, подумай как можно упростить

2023-03-19 15:33 UTC, Ivan6813 commented on src/components/main/main.jsx
> +          !isCategoriesLoading &&
попробуй упростить

2023-03-19 15:33 UTC, Ivan6813 commented on src/components/schedule/schedule.jsx
> +                  i === holiday.find((n) => n === i) && styles.holiday,
слишком большое и сложное условие, ты же сам его через пару недель не сможешь быстро прочитать и разобраться что к чему) подумай как это упростить

2023-03-20 05:45 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 96%.
Общее количество тестов: 25.
Количество непройденных тестов: 1.
***
**1-all-buttons.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/1-all-buttons.png)
***
**10-selected-day.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/10-selected-day.png)
***
**11-booking-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/11-booking-error.png)
***
**12-booking-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/12-booking-success.png)
***
**13-booking-edit-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/13-booking-edit-modal-view.png)
***
**14-modal-edited-date.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/14-modal-edited-date.png)
***
**15-rate-modal.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/15-rate-modal.png)
***
**16-rate-modal-mobile.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/16-rate-modal-mobile.png)
***
**17-rate-filled.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/17-rate-filled.png)
***
**18-comments-updated-sort.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/18-comments-updated-sort.png)
***
**2-booking-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/2-booking-modal-view.png)
***
**3-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/3-mobile-view.png)
***
**4-january.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/4-january.png)
***
**5-december-2022.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/5-december-2022.png)
***
**6-february.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/6-february.png)
***
**7-today-is-friday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/7-today-is-friday.png)
***
**8-today-is-saturday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/8-today-is-saturday.png)
***
**9-today-is-sunday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/9-today-is-sunday.png)
***
**booking and book rate -- booking edit modal -- check cancel booking error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20cancel%20booking%20error%20(failed).png)
***
**edit-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgenii77777/1679291133/edit-mobile-view.png)

2023-03-20 06:21 UTC, merged